server:
  port: 19090

eureka:
  client:
    register-with-eureka: false  # ?? Eureka ??? ? ??? ???? ??
    fetch-registry: false  # ?? Eureka ??? ?????? ???? ??
  server:
    enable-self-preservation: false  # ?? ?? ?? ????